apiVersion: v1
kind: Service
metadata:
    name: postgres-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: postgres
    ports:
        - port: 5432
          targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
    name: postgresql-data-claim # Sets name of PV
spec:
    accessModes:
        - ReadWriteOnce # Sets read and write access
    resources:
        requests:
            storage: 5M # Sets volume size
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployemnt
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres
    template:
        metadata:
            labels:
                component: postgres
        spec:
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                      claimName: postgresql-data-claim
            containers:
                - name: postgres
                  image: "postgres:latest"
                  env:
                      - name: POSTGRES_PASSWORD
                        value: "postgres_password"
                  ports:
                      - containerPort: 5432
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
                        subPath: postgres
#   - name: REDIS_HOST
#     value: "redis"
#   - name: REDIS_PORT
#     value: "6379"
#   - name: PG_USER
#     value: "postgres"
#   - name: PG_PASSWORD
#     value: "postgres_password"
#   - name: PG_HOST
#     value: "postgres"
#   - name: PG_DATABASE
#     value: "postgres"
