apiVersion: v1
kind: Service
metadata:
    name: postgres-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: postgres
    ports:
        - port: 5432
          targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployemnt
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres
    template:
        metadata:
            labels:
                component: postgres
        spec:
            containers:
                - name: postgres
                  image: "postgres:latest"
                  env:
                      - name: POSTGRES_PASSWORD
                        value: "postgres_password"
                  ports:
                      - containerPort: 5432
#   - name: REDIS_HOST
#     value: "redis"
#   - name: REDIS_PORT
#     value: "6379"
#   - name: PG_USER
#     value: "postgres"
#   - name: PG_PASSWORD
#     value: "postgres_password"
#   - name: PG_HOST
#     value: "postgres"
#   - name: PG_DATABASE
#     value: "postgres"
